#:kivy 2.1.0




<MainWidget>:

    gameSpace: gameSpace
    rightPanel: rightPanel
    overlay: overlay


    BoxLayout:
        orientation: 'horizontal'
        spacing: 0
        size: root.size

        GameSpace:
            id: gameSpace
            size_hint: [0.7, 1]


        RightPanel:
            id: rightPanel
            size_hint: [0.3, 1]
            size_hint_max_x: 325

    Overlay:
        id: overlay
